//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq; // Add this using directive for LINQ methods

    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Apartment = new HashSet<Apartment>();
        }

        public int ID { get; set; }
        public int ResidentialComplexID { get; set; }
        public int StreetID { get; set; }
        public string Number { get; set; }
        public bool IsDeleted { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartment { get; set; }
        public virtual ResidentialComplex ResidentialComplex { get; set; }
        public virtual Street Street { get; set; }

        // Computed property for sold apartments
        public int SoldApartmentsCount => Apartment?.Count(a => a.IsSold) ?? 0;

        // Computed property for available apartments
        public int AvailableApartmentsCount => Apartment?.Count(a => !a.IsSold) ?? 0;
    }
}
