//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsoftEntities : DbContext
    {
        private static EsoftEntities _context;
        public EsoftEntities()
            : base("name=EsoftEntities")
        {
        }
        public static EsoftEntities GetContext()
        {
            if (_context == null)
            {
                _context = new EsoftEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<CostDetails> CostDetails { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<ResidentialComplex> ResidentialComplex { get; set; }
        public virtual DbSet<Street> Street { get; set; }
    }
}
